#!/usr/bin/env bash
# Copyright, 2025 Specter Ops, LLC.  All rights reserved.

BH_USER="apihound"

# Try to start each known postgresql service
for i in postgresql@17-main postgresql; do
	service $i start
	if [ $? -eq 0 ]; then
		echo "Started $i"
		break
	fi
done

# Wait for it to be available
ATTEMPTS=0
until $(su postgres -c "psql -l &> /dev/null") || test $ATTEMPTS -ge 5; do
	echo "Waiting for Postgres..."
	sleep 2
	let "ATTEMPTS=ATTEMPTS+1"
done

if ! getent group $BH_USER >/dev/null; then
    addgroup --quiet --system $BH_USER
fi
if ! getent passwd $BH_USER >/dev/null; then
	adduser --quiet --system --ingroup $BH_USER --home /var/lib/apihound --no-create-home $BH_USER
fi

# Create PostgreSQL role and database
if ! su postgres -c "psql -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$BH_USER'\"" | grep -q 1; then
    su postgres -c "psql -c \"CREATE ROLE $BH_USER WITH LOGIN CREATEDB;\""
fi
if ! su postgres -c "psql -lqt" | cut -d \| -f 1 | grep -qw apihound; then
    su postgres -c "createdb -O $BH_USER apihound"
fi

# Update our admin password
ADMIN_PASSWORD="$(openssl rand -hex 32)"
jq ".default_admin.password = \"$ADMIN_PASSWORD\"" /etc/apihound/bhapi.json.default > /etc/apihound/bhapi.json

chown -R $BH_USER:$BH_USER /var/lib/apihound
chown -R $BH_USER:$BH_USER /var/log/apihound
chown -R $BH_USER:$BH_USER /etc/apihound/*
chmod 600 /etc/apihound/bhapi.json.default
chmod 600 /etc/apihound/bhapi.json

service apihound start

echo "============ APIHound Community Edition has been configured."
echo "  The initial admin password is '$ADMIN_PASSWORD'"
echo "  It can be accessed at http://localhost:8080"
